### ISSUE TITLE
singleWindowApplication() does not exit

### ISSUE THREAD

**Issue by AshStefanOltmann** [JetBrains/compose-jb#1021]
The documentation for `singleWindowApplication()` on https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new states that `you don't need custom closing logic`, but closing the Window does not kill the process. The application keeps running and must be externally killed.

My assumption is that `::exitApplication` would be called.

**Comment by akurasov** [comment]
@AshStefanOltmann do you have a reproducer? singleWindowApplication uses ::exitApplication inside

**Comment by AshStefanOltmann** [comment]
> @AshStefanOltmann do you have a reproducer? singleWindowApplication uses ::exitApplication inside

No, I don't have a public producer for that. If you can't reproduce this behavior I will need to build one to find out what's causing the problem.

**Comment by akurasov** [comment]
@AshStefanOltmann as I said, singleWindowApplication is a wrapper around Window(::exitApplication). As CMPP is open source, you can see it yourself. 

Also we use is extensively and never faced such issue. It sounds really strange to me.

**Comment by AshStefanOltmann** [comment]
> @AshStefanOltmann as I said, singleWindowApplication is a wrapper around Window(::exitApplication). As CMPP is open source, you can see it yourself.
> 
> Also we use is extensively and never faced such issue. It sounds really strange to me.

Yeah, can you please point me to the source code of `Window_desktopKt`?
I can't seem to find it to look up how I would implement my code with the `Window` composable.

I use the parameters `icon`, `title` & `state` which seem not to be available there.

**Comment by igordmn** [comment]
```
Yeah, can you please point me to the source code of Window_desktopKt?
```
It is [here](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui/src/desktopMain/kotlin/androidx/compose/ui/window/Window.desktop.kt;l=252;drc=be961a52611b528bcbbffd50c390b8b6df4ccfeb)

`exitApplication` means that we end `application` block, not exit the process. The process will exit when we reach the end of `main` function, and there is no any background non-daemon thread running. If your application don't exit, most certainly there is such a thread somewhere.

Try to look if somewhere in your code there is a thread that never ends (a thread with an infinite loop or some thread pool created via `Executors`).

This code illustrate the problem:

```
import androidx.compose.ui.window.singleWindowApplication
import kotlin.concurrent.thread
import kotlin.system.exitProcess

fun main() {
    val thread = thread {
        try {
            while (true) {
                Thread.sleep(1000)
            }
        } catch (e: InterruptedException) {
            // ignore
        } finally {
            println("END")
        }
    }

    singleWindowApplication {

    }

//    thread.interrupt()
//    thread.join()

//    Call `exitProcess` only if you sure that there is no important background thread running
//    exitProcess(0)
}
```
If we uncomment `thread.interrupt()`, the app process will end.

If we uncomment `exitProcess` - the process will end too, but I don't recommend to use it, because all `finally` blocks will never be called, and more importantly - some code will stop in the middle of execution. This will lead to incomplete writing to disk / uploading to network, etc.
You can call it, if you sure, that all IO operations have ended before `exitProcess`.

We called `exitProcess` in the old window API (in `AppWindow`), but don't call in the new API, as it very deadly behavior for many applications.

Another code that illustrates the issue, using `Executors`:
```
import androidx.compose.ui.window.singleWindowApplication
import java.util.concurrent.Executors

private val executor = Executors.newSingleThreadExecutor()

fun main() {
    executor.submit {  }

    singleWindowApplication {

    }
// uncomment this to properly clean resources
//    executor.shutdown()
}
```

**Comment by AshStefanOltmann** [comment]
> We called `exitProcess` in the old window API (in `AppWindow`), but don't call in the new API, as it very deadly behavior for many applications.

Ah, ok. I understand now the change in behavior. Thank you.

Closing the issue as it's not a bug and I have to look out for running background threads.

Maybe you should consider documenting this anyway, because now it's not quite clear that `exitApplication()` just ends the the `singleWindowApplication` and nothing more.

**Comment by igordmn** [comment]
>Maybe you should consider documenting this anyway, because now it's not quite clear that exitApplication() just ends the the singleWindowApplication and nothing more.

Good idea 👍 , we will write about this

**Comment by AshStefanOltmann** [comment]
I also found the problem: I use Sentry.io for Crash Logging and it needs an explicit call to `Sentry.close()` after the `singleWindowApplication` block. I would have suspected these threads to be daemons, but now I know more.

My application is pretty complex, but I can confirm that with end of the `singleWindowApplication` all coroutines and other stuff finalizes properly. So all is good. 👍

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5325">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
