### ISSUE TITLE
Shared multiplatform code isn't highlighted in compose-jb app

### ISSUE THREAD

**Issue by soniccat** [JetBrains/compose-jb#1039]
Hi, I've managed to run my compose-jb app with a multiplatform shared library here https://github.com/soniccat/WordTeacher/tree/desktop-second-attempt (desktopApp module). 

I include my shared code this way: 
`implementation(project(":shared"))`
https://github.com/soniccat/WordTeacher/blob/desktop-second-attempt/desktopApp/build.gradle.kts

But I see shared code isn't highlighted in my IDE:
<img width="1552" alt="Screen Shot 2021-08-11 at 10 40 16" src="https://user-images.githubusercontent.com/147129/128990214-fbe6f2a4-e143-40f2-bf6b-3f0c3179836d.png">

I see this error when I bring the cursor to unhighlighted code:
<img width="488" alt="Screen Shot 2021-08-11 at 10 46 53" src="https://user-images.githubusercontent.com/147129/128990587-b5918d27-8437-481c-afd9-78b8a18f9adc.png">

In androidApp in the same repository I don't have this problem.

**My IDE:**
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.2.3
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 8
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.toml.lang, org.jetbrains.kotlin, com.jetbrains.kmm, org.jetbrains.compose.desktop.ide, com.squareup.sqldelight

**Comment by akurasov** [comment]
Hi! I loaded your current project into the same version(removed all ios staff, but it shouldn't impact the issue):
Android Studio Arctic Fox | 2020.3.1
Build #AI-203.7717.56.2031.7583922, built on July 26, 2021
Runtime version: 11.0.10+0-b96-7281165 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 11.4
GC: G1 Young Generation, G1 Old Generation
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: org.jetbrains.kotlin

and everything is fine. What are the version of Kotlin and KMM plugins that you use? 

Do you still have this issue now? Maybe you changed something and that's why it is fine on my pc.

**Comment by soniccat** [comment]
Hi, I haven't changed  desktop-second-attempt branch. I suppose that the highlight issue might happen after switching between targets. Could you try to build android target and then a desktop target?

I'll try to reproduce it again this weekend and write back then.

**Comment by akurasov** [comment]
It is an issue of Kotlin plugin - https://youtrack.jetbrains.com/issue/KTIJ-19504. The fix will be released in 1.5.31

**Comment by soniccat** [comment]
I see that I had the problem with 1.5.20 kotlin and 1.5.20 KMM plugin. I've updated the plugin and when I come back to compose-jb I'll check again and reopen the bug if needed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5312">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
