### ISSUE TITLE
Compose Multiplatform Library

### ISSUE THREAD

**Issue by wakaztahir** [JetBrains/compose-jb#1212]
I have a android compose library that I would like to separate from the project
I want to make it multiplatform since it only depends upon compose

Now , I went into project creation dialogue in the Intellij Idea and selected library under multiplatform

**First Problem :** I don't know which dependencies to add to different places in the sourceSets , there are different sections for each platform
**Second Problem :** Since Jetpack Compose doesn't target native , so I removed the native folders and now its not recognizing other modules

What I would like is a simple way to create a multiplatform jetpack compose library

**Comment by wakaztahir** [comment]
--- currently trying to create a project

**Comment by akurasov** [comment]
I would suggest you to restart and begin from Compose Multiplatform wizard target. It will contain all dependency. 

I highly recommend to use idea 2012.2.2, as it contains latest wizard with some bugs fixed in MPP template.

**Comment by wakaztahir** [comment]
and How do I publish it as a library

I am an android developer , in android a module can be added which can be configured and published as a library using maven publish
and in the main / app / sample module I can write code to test out the library , how can I achieve this , where do I put the code to test out the library 

should i go into the project structure and add a global library ?

**Comment by wakaztahir** [comment]
Where do I put my compose library code since its common for all of libraries since its common for all the platforms , android , android and other
but I am guessing the imports would be different and desktop version would import from desktop compose library so I would have to copy paste all of my code and change imports for different platforms ?
this is not right , is it ?

**Comment by wakaztahir** [comment]
since all of the code is in the common module , how do I publish it so it would work for all the platforms ?

**Comment by wakaztahir** [comment]
Ok I've read this https://kotlinlang.org/docs/multiplatform-library.html#summary

Is this same for compose or different , since this includes native platform and compose doesn't have any , so if I publish would it make a difference or would it publish fine ?

**Comment by RedStoneCats101** [comment]
hope this helps https://kotlinlang.org/docs/mpp-publish-lib.html#structure-of-publications

**Comment by akurasov** [comment]
Default project is published for both platforms. Please check how it is organized.

**Comment by wakaztahir** [comment]
So I wanted to publish github packages and this is what I got
![Capture](https://user-images.githubusercontent.com/42442700/135833780-7cd699a3-03d1-4443-bb7d-dd8f66ac42e1.PNG)

The problem is when I use my library from github packages , I can find its code in common-android module and common-desktop module but in common main its not appearing as if I did not add the library however I did

![Captur2e](https://user-images.githubusercontent.com/42442700/135833969-aa1019d5-a198-4b33-afbe-54fd21a3160c.PNG)

I can call its code in `DesktopMain` & `AndroidMain` inside the `common` module but inside `CommonMain` the code is not available , even though the common package has clearly been published
The platforms are same as well , so why code not appearing

**Comment by wakaztahir** [comment]
I would like to add web to the project, how can I add it to the existing project , help ?

**Comment by wakaztahir** [comment]
I can't call library code in CommonMain , what could be the problem ?

**Comment by akurasov** [comment]
I think it is more question about mpp publication rather than about Compose. I'd recommend you to ask it in #multiplatform channel of kotlinlang slack. 

Probably it would be helpful, if you create small reproducer without Compose - just small Common library using only stdlib and see if you can use it from common sourceSet of an App.

**Comment by mikepenz** [comment]
@wakaztahir I actually went through similar struggles this week, having no sources in the android dependency, or it resulting in conflicts for android (I am using the official android compose builds in the app I am integrating) vs the compose version for compose desktop. 

What I ended up doing:
- have jb-compose only as `compileOnly`
- also ensure to have proguard / r8 disabled (or the right rules) so it won't strip the sources from your `aar`
- only publish the release artifact for android (otherwise it would have struggle to choose the right variant)
- using the `com.vanniktech.maven.publish` library to publish the artifacts

The `build.gradle.kts`: https://github.com/mikepenz/multiplatform-markdown-renderer/blob/develop/multiplatform-markdown-renderer/build.gradle.kts

You can see the full repo here: https://github.com/mikepenz/multiplatform-markdown-renderer

Hope this can help you with your project

**Comment by akurasov** [comment]
>>I suspect that this error is related to proguard
Can you try to disable ProGuard and see if the issue persists?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5240">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
