### ISSUE TITLE
Web: TextInput doesn't work, it just eats keypresses

### ISSUE THREAD

**Issue by bitspittle** [JetBrains/compose-jb#1300]
This works - it renders a text field you can type in:

```
    renderComposable(rootElementId = "root") {
        Input(InputType.Text)
    }
```

This does not. It renders a text field that flashes when you type in it but no text comes out.

```
    renderComposable(rootElementId = "root") {
        TextInput()
    }
```

It's possible this is intentional behavior - like, I can imagine you're supposed to hook up a listener and without it it rejects the keypresses maybe. But if that's the case, then the documentation should be a lot clearer about what to do in the common case.

This is happening with 1.0.0-beta1

**Comment by PaoloConte** [comment]
This is happening from the beta version, while it works correctly with the alpha version.
Looking into the JS code it looks like it's trying to parse the text as a Week object
```
InputTypeWithStringValue.prototype.inputValue_5tgw3j_k$ = function (event) {
    return Week_getInstance().valueAsString_5tgw3j_k$(event);
  };
```

**Comment by eymar** [comment]
IDE can offer some documentation about TextInput and Input.
The behaviour is indeed intentional. The behaviour in alpha was correct in some cases, but invalid in other cases. Here is why - https://github.com/JetBrains/compose-jb/issues/925

TextInput is a controlled variant of input (it changes only when backing state changes), whereas plain Input by default is not controlled. In most cases controlled input should be enough.

`Week_getInstance().valueAsString_5tgw3j_k$(event);` is a typo which by a coincidence doesn't break anything as both TextInput and WeekInput use String as an input value type.

Despite the behaviour is correct, I'll keep this issue open until we improve the docs.

**Comment by eymar** [comment]
we've added some explanations about controlled and uncontrolled inputs here - https://github.com/JetBrains/compose-jb/tree/master/tutorials/Web/Controlled_Uncontrolled_Inputs Hope it gives some clarity (anyway, it's open for discussion and improvements)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5231">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
