### ISSUE TITLE
Setted the background color for DropdownMenu, but the corner color is white

### ISSUE THREAD

**Issue by GaoXing0608** [JetBrains/compose-jb#1355]
![image](https://user-images.githubusercontent.com/47878271/140246498-11a7f401-bec1-42f9-b525-35df8c65de3e.png)

**Comment by akurasov** [comment]
Could you share the reproducer code, please?

**Comment by GaoXing0608** [comment]
> Could you share the reproducer code, please?

The debug code as the follows. 

@Composable
@Preview
fun App() {
    var text by remember { mutableStateOf("Hello, World!") }
    var dropdownExpanded by remember { mutableStateOf(false) }

    DesktopMaterialTheme{

        Box(
            modifier = Modifier.fillMaxSize()
                .background(Color(43, 43, 43))
        ) {
            Box{
                Button(onClick = {
                    text = "Hello, Desktop!"
                    dropdownExpanded = true
                }) {
                    Text(text)
                }

                DropdownMenu(
                    expanded = dropdownExpanded,
                    onDismissRequest = {
                        dropdownExpanded = false
                    },
                    modifier = Modifier.background(Color(44, 44, 44))
                ) {
                    DropdownMenuItem(
                        onClick = {
                            dropdownExpanded = false
                        }
                    ) {
                        Text(
                            text = "Dropdown Item",
                            color = Color.White
                        )
                    }
                }
            }
        }
    }
}

![image](https://user-images.githubusercontent.com/47878271/140894291-118330c4-55cd-47ca-854b-1bdf895968f6.png)

**Comment by akurasov** [comment]
I think it is a material shade effect. It will be more visible if you use 192-192-192 color. And if you use 0-0-0 it will disappear at all.

**Comment by Tylll3Hka** [comment]
It was not possible to remove the white lines on the corners

**Comment by malliaridis** [comment]
@Tylll3Hka I looked into this issue and found out that it is a theme related problem. To be precise you are having these white colors because it is a light theme-related efffect that applies on a dark component (dark because it is styled as such). When switching to dark theme or overriding the surface color of the theme you can fix this.

I recommend you to make use of the theme's dark and light theme feature and don't manually set the background colors for such modals (would also reduce unnecessary customizations). For customizing the theme you can look up instructions online, one of them is the [Android Developer page](https://developer.android.com/jetpack/compose/designsystems/custom).

For a quick and dirty fix that allows you to customize the theme locally at the place of definition you can wrap your `DropdownMenu` with a custom theme:

```kotlin
// Either use darkColorScheme() (M3) or lightColorScheme(surface = Color(44, 44, 44))
// or for Material 2 darkColors() / lightColors(surface = Color(44, 44, 44))
MaterialTheme(colorScheme = darkColorScheme()) {
  DropdownMenu(
    expanded = dropdownExpanded,
    onDismissRequest = { dropdownExpanded = false },
    modifier = Modifier.background(Color(44, 44, 44))
    ) {
      DropdownMenuItem(
      onClick = { dropdownExpanded = false },
      text = {
        Text(
          text = "Dropdown Item",
          color = Color.White // <- Text color on dark theme is automatically white and therefore this is not necessary
        )
      },
    )
  }
}
```

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5193">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
