### ISSUE TITLE
The compiled jar is too large

### ISSUE THREAD

**Issue by purofle** [JetBrains/compose-jb#1434]
I compiled a jar with `./gradlew packageUberJarForCurrentOS` and it works well.But this jar is too large(almost 75mb).

After unpacking this jar, I found that there is almost a complete kotlin in `jar/org/jetbrains/kotlin`.

Is it a bug?
(I'm sorry for my English is very poor)

**Comment by olonho** [comment]
What is expected behavior for you? This jar is intended to contain all deps.

**Comment by purofle** [comment]
Remove&nbsp;unwanted&nbsp;dependencies&nbsp;(such&nbsp;as&nbsp;the&nbsp;kotlin&nbsp;compiler)


---Original---
From: &quot;Nikolay ***@***.***&gt;
Date: Mon, Nov 22, 2021 17:44 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [JetBrains/compose-jb] The compiled jar is too large (Issue#1434)




 
What is expected behavior for you? This jar is intended to contain all deps.
 
&mdash;

**Comment by AlexeyTsvetkov** [comment]
@purofle you can use Proguard to shrink the resulting jar guardsquare.com/manual/setup/gradle

However, this process might not work completely automatically, because ProGuard might remove some actually used classes (e.g. classes that are used through reflection). Sadly, we can't fully automate removal of potentially unnecessary classes.

**Comment by MrStahlfelge** [comment]
Please see #1174 for some suggestions how to use ProGuard

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5178">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
