### ISSUE TITLE
[Web app] How to handle back/forward and refresh buttons on the browser

### ISSUE THREAD

**Issue by antranvn** [JetBrains/compose-jb#1580]
Hi guys,
I'm trying to handle back/forward and refresh buttons. For example in the "todo" application.
Can you give any tutorial or document on that?

**Comment by hfhbd** [comment]
Back and forward buttons are usually supported by some navigation/routing libraries. The refresh button can't be controlled by a JS application, because it reloads the current page, including your current JS app/state.

**Comment by Schahen** [comment]
Hi @antranvn ! We intentionally don't implement any routing layer in compose itself - as of now we want to keep it as minimal as it makes sense. Like Philip told above, there's a plenty of navigation / routing libraries in javascript (and even narrower in kotlin / js) ecosystem) which are easily integrated with compose. 

If you'll have troubles with integrating library of your choice because of technical limitations on our side - feel free to report an issue and we'll see what can be done!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5135">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
