### ISSUE TITLE
How to hide application icon from taskbar?

### ISSUE THREAD

**Issue by habibg1232191** [JetBrains/compose-jb#1767]
Here is an example in [awt](https://stackoverflow.com/questions/7461477/how-to-hide-a-jframe-in-system-tray-of-taskbar).

**Comment by avdeev-dima-tutu** [comment]
This question is about Windows OS

**Comment by avdim** [comment]
This question is about Windows target

**Comment by avdim** [comment]
I think, @habibg1232191, want to achieve something like this: https://roundwide.com/implementing-system-tray-app-with-wpf-and-mvvm/
Maybe in JVM it can be difficult...

**Comment by habibg1232191** [comment]
@avdim that's right. What I wanted

**Comment by avdim** [comment]
I made sample with the desired behaviour https://github.com/avdim/compose-desktop-not-shown-in-task-bar
@habibg1232191  Can you please check it?

**Comment by igordmn** [comment]
Is the question about how to hide the window from taskbar, when it is opened, or - how to hide the window into tray instead of closing it?

If the second, then - as avdim described (or [this way](https://github.com/JetBrains/compose-jb/blob/master/tutorials/Window_API_new/README.md#hide-the-window-into-the-tray) with Composable API).

If the first, then it is probably impossible with AWT/Swing API. We need to use a native API: retrieve `ComposeWindow.windowHandle`, and write platform-specific logic via JNI. I don't know exactly what API is needed for that, but it is possible, as Toolbox has the same issue, and have fixed it. There is another issue will arise - we can hide window from the taskbar only if it is already visible. So there will be a small glitch - window appears on the taskbar for 300ms. It probably can't be avoided as far as we use Swing as implementation for Compose.

**Comment by avdim** [comment]
> Is the question about how to hide the window from taskbar, when it is opened, or - how to hide the window into tray instead of closing it?
> 
> If the second, then - as avdim described (or [this way](https://github.com/JetBrains/compose-jb/blob/master/tutorials/Window_API_new/README.md#hide-the-window-into-the-tray) with Composable API).
> 
> If the first, then it is probably impossible with AWT/Swing API. We need to use a native API: retrieve `ComposeWindow.windowHandle`, and write platform-specific logic via JNI. I don't know exactly what API is needed for that, but it is possible, as Toolbox has the same issue, and have fixed it. There is another issue will arise - we can hide window from the taskbar only if it is already visible. So there will be a small glitch - window appears on the taskbar for 300ms. It probably can't be avoided as far as we use Swing as implementation for Compose.

My sample hide window from taskbar only in Windows OS and some Linux distributions. It achieves with usage JDialog() instead of JFrame()

**Comment by igordmn** [comment]
> It achieves with usage JDialog() instead of JFrame()

Indeed, thanks!

Interesting, that `ComposeDialog` shows the icon in the taskbar. I have fixed it [here](https://github.com/JetBrains/androidx/pull/177).

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1767">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
