### ISSUE TITLE
mouseClickable shouldn't fire click when detectTransformGestures on parent handles gesture

### ISSUE THREAD

**Issue by jimgoog** [JetBrains/compose-jb#1779]
Drag your mouse over the following text. Observe that mouse click fires on the child despite the fact a pan gesture was detected by the parent.  Issue appears to be on the desktop side in mouseClickable . We normally/should solve this by watching for consumed events while waiting for the "up". See waitForUpOrCancellation as an example.

```
import androidx.compose.foundation.ExperimentalFoundationApi
import androidx.compose.foundation.gestures.detectTransformGestures
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.mouseClickable
import androidx.compose.material.Text
import androidx.compose.ui.Modifier
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.input.pointer.pointerInput
import androidx.compose.ui.window.Window
import androidx.compose.ui.window.application

@OptIn(ExperimentalFoundationApi::class)
fun main() = application() {
    Window(onCloseRequest = ::exitApplication) {
        Box(Modifier.fillMaxSize().pointerInput(Unit) { detectTransformGestures { centroid, pan, zoom, rotation -> println("parent detected gesture $centroid $pan $zoom $rotation") }}) {
            Box(Modifier.fillMaxSize().mouseClickable { println("child click detected") }) {
                Text("Just some content")
            }
        }
    }
}
```

cc @igordmn @olonho

**Comment by igordmn** [comment]
Fixed in https://github.com/JetBrains/androidx/pull/178.

By the way, `mouseClickable` is a temporary workaround. It still doesn't support auto-hover, auto-action on Enter key, mouse slop detection. 

Also it doesn't support detection of simultaneously pressed buttons (right click when the left button is pressed, for example).

We [tried to introduce](https://android-review.googlesource.com/c/platform/frameworks/support/+/1832415) info about pressed buttons in the past into common `clickable`. We plan to return to this feature someday, and deprecate `mouseClickable`

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1779">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
