### ISSUE TITLE
why there is no code

### ISSUE THREAD

**Issue by zcg** [JetBrains/compose-jb#1796]
the link is [https://github.com/JetBrains/compose-jb/tree/master/tooling/compose-intellij-platform](https://github.com/JetBrains/compose-jb/tree/master/tooling/compose-intellij-platform)

I installed this plugin, but I don't know how to use it, so I want to study what this plugin does, but when I found the location of the source code, I found that there is no code in the src directory, only this resources directory

the plugin name is Compose for IDE Plugin Development ​(Experimental)​
the link is [https://plugins.jetbrains.com/plugin/18439-compose-for-ide-plugin-development-experimental-](https://plugins.jetbrains.com/plugin/18439-compose-for-ide-plugin-development-experimental-)

**Comment by olonho** [comment]
It is infrastructure plugin packaging Compose runtime as IDEA plugin, so not sure what exactly would you like to learn.

**Comment by akurasov** [comment]
@zcg the purpose of the plugin is the following: help to build your own plugins with Compose MP usage.

Without this plugin, you would've to bundle Compose for all platforms into your plugin, that would make it's size enormous. Now, instead of it, you can just add reference to our plugin and this is it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-1796">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
