### ISSUE TITLE
Unresolved reference: LazyVerticalGrid on Android

### ISSUE THREAD

**Issue by ynsok** [JetBrains/compose-jb#2061]
Hi, 

I'm developing a multiplatform application targeting JVM and Android. As you can see on the screen, when I'm trying to run the application on Android I'm receiving this error, while on the JVM everything is working correctly. I have to mention when substituting imports `androidx.compose.foundation.lazy.LazyVerticalGrid` on android is working but on the desktop is crashing because it is the wrong path.

![image](https://user-images.githubusercontent.com/30358511/168305291-3bd604ae-142c-4a2a-92b6-f58ab1be7d5b.png)

kotlinVersion: `1.6.21`
compose: `1.2.0-alpha01-dev679`

**Comment by happyjun** [comment]
> Still actual in `1.2.0-alpha01-dev741`

I use 1.2.0-alpha01-dev741 the problem still exist, please have a look

**Comment by StefanOltmann** [comment]
In release v1.2.0 the `LazyVerticalGrid` seems to be gone.

**Comment by norcisa-andy** [comment]
I am experiencing the same on v1.2.1

**Comment by StefanOltmann** [comment]
@norcisa-andy It's still there. I discovered that it moved to another package.

It's now `androidx.compose.foundation.lazy.**grid.**LazyVerticalGrid`

**Comment by sooshil** [comment]
I didn't find 'lazy' package in androidx.compose.foundation**.lazy.**grid.LazyVerticalGrid.
compose_version = '1.3.2'

**Comment by iletleon** [comment]
compose 1.3.2 遇到同样问题

**Comment by hodakl099** [comment]
compose Version` 1.2.0-beta02 ` fixed it to me

**Comment by dima-avdeev-jb** [comment]
I made a sample with usage of LazyVerticalGrid in commonCode between Android and Desktop:
https://github.com/dima-avdeev-jb/desktop-android-lazy-vertical-grid
It work's fine.

**Comment by igordmn** [comment]
This is no longer reproducible in 1.2.2. This was because `LazyVerticalGrid` was/is experimental, and we have incompatible APIs in different versions of `compose.foundation` (`androidx.compose.foundation.lazy.LazyVerticalGrid` in common/desktop, `androidx.compose.foundation.lazy.grid.LazyVerticalGrid` in Android). In case of dev releases we can use different versions for Desktop and Android targets. This is not the case for stable releases though, everything should be okay in them.

We will look how we can improve dev releases. Usually when we rebase only on stable commits of `androidx` repository, there should be no such issues.

[Similar issue](https://github.com/JetBrains/compose-jb/issues/2284) for material3 library, that became stable only recently.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2061">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
