### ISSUE TITLE
Kotlin 1.7.21 compatibility and adding an opt-out for compatibility checks

### ISSUE THREAD

**Issue by ZacSweers** [JetBrains/compose-jb#2459]
Something changed recently (possible 1.3.1?) where using a newer kotlin version (in this case 1.7.21) fails the build now.

```
This version of Compose Multiplatform doesn't support Kotlin 1.7.21. Please see https://github.com/JetBrains/compose-jb/blob/master/VERSIONING.md#kotlin-compatibility to know the latest supported version of Kotlin.
```

This is surprising as compose/kotlin support should be left to the compose compiler no? I'm not sure why this project is adding its own layer of checks, and it prevents us from both updating Kotlin versions and testing upcoming versions when they're available. The compose compiler plugin allows for opting out of this failure, could one be added for compose-jb as well?

**Comment by igordmn** [comment]
> possible 1.3.1

This layer of checks was added in [Compose Multiplatform 1.2.0](https://github.com/JetBrains/compose-jb/releases/tag/v1.2.0), when we added [the feature of supporting multiple Kotlin's](https://github.com/JetBrains/compose-jb/pull/2366), in which our Gradle plugin chooses appropriate Compose Compiler according to the applied version of Kotlin.

Compose Compiler was always added behind the scenes in Compose Multiplatform (in compare to Jetpack Compose, where it is added explicitly). For users who knows about that there is Compose Compiler, there is a way to explicitly configure Compose Compiler. And because it is configured explicitly, we bypass this new layer of checks:

```
compose {
    kotlinCompilerPlugin.set("org.jetbrains.compose.compiler:compiler:1.3.2.1") // see versions here https://mvnrepository.com/artifact/org.jetbrains.compose.compiler/compiler
}

kotlinOptions.freeCompilerArgs += listOf(
    "-P",
    "plugin:androidx.compose.compiler.plugins.kotlin:suppressKotlinVersionCompatibilityCheck=true"
)
```

What we lack right now is proper documentation, and maybe proper DSL. We will fix that. Maybe it will be like that:
```
compose {
    kotlinCheck = false
}
```
or
```
compose {
    kotlinCompilerPlugin.set(ComposeCompilers.latest("suppressKotlinVersionCompatibilityCheck=true")
}
```
still not sure

> updating Kotlin versions and testing upcoming versions when they're available

Most probably only hotfixes will be compatible (if we lucky), the major Kotlin releases usually broke the compatibility, and we had to wait for the new Jetpack Compose Compiler (and then for the new hotfix for Compose Multiplatform that implicitly uses it, we will release it approximately after a week after Jetpack Compose Compiler)

**Comment by ZacSweers** [comment]
A DSL would be helpful 👍. I can send a PR if you want? The main problematic snippet is [this](https://github.com/JetBrains/compose-jb/blob/2027e4bddd745a306e17c7ef87a07dfd09d3316a/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/internal/ComposeCompilerArtifactProvider.kt#L21-L28), not configuring compose-compiler itself.

**Comment by ZacSweers** [comment]
Actually looks like it's not propagating the compose compiler arguments correctly in 1.2.2

https://github.com/slackhq/circuit/pull/340


```kotlin
  pluginManager.withPlugin("org.jetbrains.compose") {
    configure<ComposeExtension> {
      kotlinCompilerPlugin.set(
        dependencies.compiler.forKotlin(libs.versions.compose.jb.kotlinVersion.get())
      )
      kotlinCompilerPluginArgs.add(
        "suppressKotlinVersionCompatibilityCheck=${libs.versions.kotlin.get()}"
      )
    }
  }
```

> e: This version (1.3.2) of the Compose Compiler requires Kotlin version 1.7.20 but you appear to be using Kotlin version 1.7.22 which is not known to be compatible.  Please fix your configuration (or `suppressKotlinVersionCompatibilityCheck` but don't say I didn't warn you!).

**Comment by igordmn** [comment]
I checked `multiplatform-template`, adding to multiple `build.gradle.kts` this:
```
compose {
    kotlinCompilerPlugin.set(dependencies.compiler.forKotlin("1.7.20"))
    kotlinCompilerPluginArgs.add("suppressKotlinVersionCompatibilityCheck=1.7.22")
}
```
and it worked.

I checked `circuit`, and indeed, it doesn't work there. It worked for the module `:samples:counter:desktop`, but didn't worked for other modules. I looked at the modules, where it failed, and find that Compose Compiler is applied separately:
```
dependencies { add(PLUGIN_CLASSPATH_CONFIGURATION_NAME, libs.androidx.compose.compiler) }
```
Not with help of Compose Multiplatform Gradle plugin. You have to add `suppressKotlinVersionCompatibilityCheck=1.7.22` to these modules manually. I added this to the global `freeCompilerArgs`:

```
"-P",
"plugin:androidx.compose.compiler.plugins.kotlin:suppressKotlinVersionCompatibilityCheck=1.7.22",
```
and removed `kotlinCompilerPluginArgs` (because setting `suppressKotlinVersionCompatibilityCheck` two times for the `:samples:counter:desktop` module will fail).

And it worked.

**Comment by ZacSweers** [comment]
got it, thanks!

**Comment by OliverO2** [comment]
Actually, it seems like this could be fixed. Given these sections:

https://github.com/JetBrains/compose-jb/blob/ab02a7125c3c4402a83d5278fae132342c6bc046/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/ComposePlugin.kt#L31

https://github.com/JetBrains/compose-jb/blob/ab02a7125c3c4402a83d5278fae132342c6bc046/gradle-plugins/compose/src/main/kotlin/org/jetbrains/compose/ComposePlugin.kt#L72-L79

Selecting tasks via `org.jetbrains.kotlin.gradle.tasks.KotlinCompile` is missing some multiplatform targets (e.g. `Js`).

Changing the import to `org.jetbrains.kotlin.gradle.dsl.KotlinCompile` (replacing `tasks` with `dsl`) catches all multiplatform targets. This works with Kotlin "jvm" and "multiplatform" Gradle plugins.

**Comment by chrisjenx** [comment]
I ran into the check seeming to not work, the thing I missed first time was making sure the `for` version matches compose multiplatform versioning, and the suppress matches you kt:

```
compose {
    val ktVer = libs.versions.kotlin.get()
    kotlinCompilerPlugin.set(dependencies.compiler.forKotlin("1.8.20"))
    kotlinCompilerPluginArgs.add("suppressKotlinVersionCompatibilityCheck=$ktVer")
}
```

IMO i think the errors should maybe be different?

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-2459">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
