### ISSUE TITLE
Any plans to use XML as a desktop layout?

### ISSUE THREAD

**Issue by FlyingYu-Z** [JetBrains/compose-jb#309]
layout use xml

**Comment by Dominaezzz** [comment]
Why? It defeats the whole point I think.

**Comment by gbaldeck** [comment]
Yeah... this is Jetpack Compose. The entire reason it was created is to avoid xml layouts and define UI using a declarative style in code.

**Comment by jimgoog** [comment]
As the progenitor of Compose, I can say that avoiding XML was not "the whole point".  The original syntax I proposed for invoking composables actually looked a lot like XML embedded into Kotlin.  The primary objective was (and still is) to encourage a declarative API instead of an imperative one and to ensure top-down data flow.

Most people, when they request XML, are requesting it because they've been taught that "separation of concerns" is a best practice.  They are correct, you do want to separate concerns, but they've erroneously conflated distinct technologies with distinct concerns.  Maybe I'll write a post with my own thoughts on the topic at some point, but in the mean time, this author does a pretty good job: https://medium.com/madhash/rethinking-separation-of-concerns-with-react-7e5de1b5c0f7

All this is to say, no, we don't intend to add XML because the Kotlin DSL we use already adequately provides the separation of concerns we're trying to achieve.

**Comment by ragunathjawahar** [comment]
@jimgoog the link that you shared (https://medium.com/madhash/rethinking-separation-of-concerns-with-react-7e5de1b5c0f7) is behind a paywall. Is there an alternative link that you can share?

**Comment by jimgoog** [comment]
Wow, since when did medium start putting up paywalls?  Terrible.

Thanks for the heads up, and thanks for finding the alternative source!

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6491">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
