### ISSUE TITLE
Chinese is not displayed completely in the TextField with singleLine=true

### ISSUE THREAD

**Issue by nekohasekai** [JetBrains/compose-jb#364]
without singleLine
![图片](https://user-images.githubusercontent.com/56506714/107419310-9c609e00-6b52-11eb-89ef-104a49959534.png)

with singleLine=true
![图片](https://user-images.githubusercontent.com/56506714/107419372-b0a49b00-6b52-11eb-85c6-0c2f5e36e9ec.png)

**Comment by olonho** [comment]
What is expected behavior?

**Comment by jimgoog** [comment]
The first screenshot is the expected behavior even when `singleLine=true`.  Notice in the first chinese character, the first screenshot includes the horizontal line at the bottom of the character.  That horizontal line is part of the character, and drawing that character without the horizontal line is incorrect.  The other second character is also cut off (missing some pixels), but it's a little less obvious at first glance.

**Comment by lizhongyue248** [comment]
The same issue. When will it be fixed？

**Comment by akurasov** [comment]
This is not only for Chinese, Latin letters are also cut - see L on the screenshot
<img width="293" alt="Screen Shot 2021-07-22 at 1 09 54 PM" src="https://user-images.githubusercontent.com/86794754/126623300-3f4a3865-a746-4522-83a5-6d8a27d80deb.png">

**Comment by lizhongyue248** [comment]
Has the issue been fixed?

**Comment by akurasov** [comment]
yes, we use another font now. Do you still have this issue?

**Comment by lizhongyue248** [comment]
I have solved the problem after upgrade the dependency. 

Thank you. This issue should be closed.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5523">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
