### ISSUE TITLE
Request add right click menu for desktop

### ISSUE THREAD

**Issue by gtf35** [JetBrains/compose-jb#445]
Right click menu is a very common and very important thing, could compose-jb provide some convenient methods to create a right-click menu, or convenient methods for listening right clicks , please? 💖

**Comment by atoktoto** [comment]
Is there a workaround for this?

**Comment by atoktoto** [comment]
There is a `DropdownMenu` that can position itself based on the parent position + some offset provided in the call itself. A there is a [documented workaround for the right click](https://github.com/JetBrains/compose-jb/tree/master/tutorials/Mouse_Events) .

**Comment by gtf35** [comment]
@atoktoto Yes, But I think there should be something that works out of the box, and I also made something similar at that time.

I just found out that they have added the official implementation, wait for me to try it 

see #539  and  https://github.com/androidx/androidx/commit/82c4f8b217b16e8488b50ffaa941231965ddbab2

**Comment by prepor** [comment]
ContextMenu was added in alpha. It should work out of the box (with material theme) for text fields and selectable text along with an ability to add custom menu items. Feel free to reopen this issue if there is something missing.

**Comment by mlthlschr** [comment]
Is there a way to enable the context menu on any arbitrary Composable, not only text fields and selectable text?

**Comment by kirill-grouchnikov** [comment]
See https://github.com/kirill-grouchnikov/aurora/blob/icicle/component/src/desktopMain/kotlin/org/pushingpixels/aurora/component/contextmenu/AuroraContextMenu.kt which is a modifier that tracks mouse events and displays the popup. Note that this is plugged into Aurora's own popup handling, so you'd replace most of it (lines 66-88) with something else.

`lastMouseEvent` will give you the coords of the clicked "point" in the bounds of that composable. Depending on how you bring up your own popup, you might need to translate it based on the window location and the composable location in the window, which you can get from `WindowScope` and `OnGloballyPositionedModifier`

**Comment by mlthlschr** [comment]
I am gonna take a look at that, thanks. I might want to check out aurora anyways, as it might help me with my project.

**Comment by hakanai** [comment]
A quirk that I thought might help the next person trying to do this.

I had this:

```kotlin
        SelectionContainer {
            @OptIn(ExperimentalFoundationApi::class)
            ContextMenuArea(
                items = {
                    listOf(
                        ContextMenuItem("Clear") {
                            appState.history.clear()
                        }
                    )
                }
            ) {
                LazyColumn { ... } 
            }
        }
```

But then when I ran, I got an error:

![image](https://user-images.githubusercontent.com/43236/194554666-ed7669e6-1730-4ce6-85f5-2995c96e743d.png)

After some fooling around, I tried it the other way around:

```kotlin
        @OptIn(ExperimentalFoundationApi::class)
        ContextMenuArea(
            items = {
                listOf(
                    ContextMenuItem("Clear") {
                        appState.history.clear()
                    }
                )
            }
        ) {
            SelectionContainer {
                LazyColumn { ... } 
            }
        }
```

And that worked fine. So there's some ordering requirement going on that isn't obvious.

- Docs for `SelectionContainer` really should say how to customise the menu it adds so that I don't have to guess
- In an ideal world, I'd like a way to order the items manually, in case I want my action to come first (esp. if it's an action you'd want to use more often than Copy)
- In other more complex GUI applications, we also have mnemonics, and sometimes even shortcuts or icons on the context menu items. It's fairly common to clone actual menu items from the main menu into the context menu, so we usually build the context menu from the action map already present in the window. In some cases we even clone entire submenus into it.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5478">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
