### ISSUE TITLE
Request: Amazon/Google/MIcrosoft cloud interaction examples.

### ISSUE THREAD

**Issue by bootrino** [JetBrains/compose-jb#462]
It would be extremely helpful if there were Jetbrains compose desktop examples that showed how to interact with the SDKs for AWS/Google/Microsoft clouds.

**Comment by jimgoog** [comment]
Those SDKs (AWS/Google/Microsoft) are already heavily documented by Amazon/Google/Microsoft respectively, and typically that documentation already includes samples using the Java programming language.

The only thing Compose does is to render the UI layer.  Everything else about your application is just standard Java.  Closing because documenting AWS/Google/Microsoft clouds is out of scope for our docs.
