### ISSUE TITLE
Can Packaging native distributions support Java 11?

### ISSUE THREAD

**Issue by drakeet** [JetBrains/compose-jb#533]
My environment must use Java 11. Can `AbstractCheckNativeDistributionRuntime` support JDK 11? 
Thanks!

**Comment by jimgoog** [comment]
When you say "My environment must use java 11", can you elaborate a little?  Are you talking about your development environment (where you do your builds) or your execution environment (where the app runs)?

If the former, the answer is no, you need jdk15 because NativeDistribution uses `jpackage` which is only available since jdk14 and realistically only really works properly after jdk15.

If the later, this comment doesn't really make sense, because the native bundles include the JVM so it really shouldn't matter what version is installed in your execution environment (you don't even need a JVM in the execution environment) because the bundled one is used.  Unless you have some really insane version requirement due to some binary dependency you are including in your package (if this is the case, you can just do the bundling yourself by manually invoking jpackage and passing in any runtime you desire).

Or am I totally missing something here?

**Comment by drakeet** [comment]
Thanks for the quick reply! In fact, the key reason is that my code needs to rely on Java 11, so it must be able to bundle JRE11. Can this project allow developers to specify JRE to bundle?

**Comment by olonho** [comment]
JDK15 is required for jpackage to work. However, as JVM is packaged, it may be not really important which version it has. Do you rely on JDK11 feature dropped in later releases? Also note, that you could target JDK11 bytecode versions in later JDK by using `-source` and `-target` arguments.

**Comment by jimgoog** [comment]
> Thanks for the quick reply! In fact, the key reason is that my code needs to rely on Java 11, so it must be able to bundle JRE11. Can this project allow developers to specify JRE to bundle?

Yes, I believe it is possible, although you would probably need to use `jpackage` and `jlink` yourself to create a runtime image and bundle the app, rather than relying on the built in `NativeDistribution` functionality we provide.  All of this is documented in the `jpackage` and `jlink` documentation and various tutorials on the internet.

As a side note: I am a bit skeptical as JVM versions are usually really good at preserving backwards compatibility, and you should probably try to find a way to update your dependencies anyway as Java11 is already almost four years old.  But if you really need to use Java11, Compose for Desktop can support that, but you will need to do the bundling yourself, it's should not be hard to achieve as I believe `jpackage` and `jlink` support this operation when invoked directly.

**Comment by AlexeyTsvetkov** [comment]
It seems to be possible to use `jlink` to build JDK 11 image, then use `jpackage` from JDK 15 just for packaging the final image, but both JDK 11 and JDK 15 will be needed. Removing build time dependency on JDK 15 requires reimplementing `jpackage`, which is doable, but unlikely.

@drakeet would you be interested in that? (i.e. using two JDKs for the build)

**Comment by drakeet** [comment]
@AlexeyTsvetkov Yes, that's what I need. If this project plugin can provide a parameter for developers to configure JRE into the native destructions, then everything will be easy.

**Comment by olonho** [comment]
Why do you care which JDK version is exactly packaged in native distribution?

**Comment by drakeet** [comment]
@olonho  One of the reasons is that I want to tailor and minify a JRE, the benefits of this are obvious, a default JRE size is so big...

**Comment by ScottPierce** [comment]
A possible solution to the JRE size is GraalVM. Graal has a native-image tool to ahead of time compile the java code and create a single executable file. It also uses significantly less memory, and has much faster startup time.

Swing is supposed to be supported in the new Java 16 equivalent GraalVM builds, which isn't in the stable channel yet though.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5463">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
