### ISSUE TITLE
Question: Why Swing instead of JavaFx underhood?

### ISSUE THREAD

**Issue by ThraaxSession** [JetBrains/compose-jb#599]
Hi together,

first, I like the idea! Finally some modern UI with less lines of code!
So this brings me here. Why do you use Swing as abstraction layer instead of JavaFX? (Which is for sure more modern.)

Regards
Gino

**Comment by jimgoog** [comment]
1.  Swing is more interoperable.  By which I mean, largely, that it's older and more "standard" so almost everything interoperates with swing, thus making it a good glue layer.
2. Intellij is written with Swing and so that was the interoperability layer that was "needed".  Other interoperability layers can be added in the future if needed/desired, contributions welcomed.

**Comment by olonho** [comment]
Also we not really use Swing as an abstraction layer, more like an interoperability and portability solution. See https://github.com/JetBrains/compose-jb/issues/519#issuecomment-804030550 for an example of JavaFX interoperability.

**Comment by ThraaxSession** [comment]
That's a good answer and makes sense! :)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6437">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
