### ISSUE TITLE
Button deformation

### ISSUE THREAD

**Issue by eric-ampire** [JetBrains/compose-jb#63]
When I want to change the corner raduis with a raduis big than 20dp, the button looks like this
![alt text](https://github.com/eric-ampire/demo-compose-desktop/blob/master/Screen%20Shot%202020-11-05%20at%2022.10.03.png?raw=true)

**Comment by olonho** [comment]
Does it behave differently from Android Compose?

**Comment by andkulikov** [comment]
I already commented on it in slack. It is currently the expected behaviour. The sum of requested top and bottom corner radiuses is larger then the height of the component. We give a priority to the top corner so it takes the requested size and the bottom takes the rest of the available one. Just make you button height larger with Modifier.height(48.dp)

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6525">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
