### ISSUE TITLE
Compose for Desktop Encryption and decryption

### ISSUE THREAD

**Issue by HeartHappy** [JetBrains/compose-jb#654]
How to implement AES text encryption and decryption in the development of MacOS desktop applications

**Comment by jimgoog** [comment]
The JVM provides a fairly complete set of encryption facilities: https://www.baeldung.com/java-aes-encryption-decryption

These are all available for use with Compose for Desktop.  Closing the issue since this is not specific to Compose for Desktop, but feel free to continue the discussion in this thread.

**Comment by HeartHappy** [comment]
thank you very much! My problem is solved

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6430">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
