### ISSUE TITLE
Question: does suspend function may affect the state variable?

### ISSUE THREAD

**Issue by Exidel** [JetBrains/compose-jb#662]
Built simple desktop app with clickable items list and showed content based on selected item.  Here [https://github.com/JetBrains/compose-jb/tree/master/tutorials/Mouse_Events#mouse-rightmiddle-clicks-and-keyboard-modifiers](url) is example how to add **mid/rightClick** event with `java.awt.MouseEvent`. When I use `Modifier.clickable{}` it return `index` of priveously selected element (Don't know why it show always previous but work right and it's ok). When use MouseEvent with suspend function it always return `index = 0` (_`var index by remember { mutableStateOf(0) }`_).

https://user-images.githubusercontent.com/80458677/118041629-af665280-b37b-11eb-8bc3-80c5498be18f.mp4

Question: Does `compose` mouse events specified to work with state variables and can `suspend function` reset remembered value of state? 
Also saw this in Modifier.clickable{} 
![mouseEvents](https://user-images.githubusercontent.com/80458677/118041969-256ab980-b37c-11eb-87d2-1e64de6490d7.jpg)

UPD: change `var index by remember { mutableStateOf(1) }` now it's always show `index = 1`

**Comment by igordmn** [comment]
When you create a lambda for pointerInput - this lambda is reused on the next recomposition, so the first created lambda catches the first passed index and doesn't see the next passed index.

If you want to use any passed argument inside pointerInput's lambda - you can use `rememberUpdatedState`:

```
val currentIndex by rememberUpdatedState(index)
...
Modifier.pointerInput(Unit) {
  ...
  println(currentIndex)
}
```

Or restart pointerInput on every index change:
```
Modifier.pointerInput(index) {
  ...
  println(index)
}
```
(but the approach with `rememberUpdatedState` in many cases is better because we don't lose all stored state inside pointerInput)

In case of `clickable` it works because we use a new passed lambda every time.

In case of `pointerInput` - we can't use a new lambda, because in fact there is no new lambda - we start an event loop inside pointerInput and don't end it.

**Comment by Exidel** [comment]
@igordmn Thx a lot for explanation and use case new (for me) feature. Find it helpfull.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5422">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
