### ISSUE TITLE
Clickable not firing on a Card

### ISSUE THREAD

**Issue by Syer10** [JetBrains/compose-jb#667]
Clickable modifiers on a card composable never fire any clicks

```
enum class Route {
    Library,
    Sources;
}

@Composable
fun MainMenuItem(route: Route, selected: Boolean, onClick: (Route) -> Unit) {
    Card(
        Modifier.clickable { onClick(route) }.fillMaxWidth().height(40.dp),
    ) {
        Text(route.name.toLowerCase())
    }
}
```
Platform: Jvm
Version that has the issue: 0.4.0-build190
Version that doesn't: 0.4.0-build185
I did not test in between those versions.

**Comment by kirill-grouchnikov** [comment]
Does it only happen when the inner composable is a `Text`?

**Comment by Syer10** [comment]
If I comment out the text and leave the other items in the row(a icon and a few spacers) it still happens

**Comment by Syer10** [comment]
Actually I just tested it with only the card, and its still not clickable, so it seems the card composable doesnt work with a clickable modifier

**Comment by igordmn** [comment]
In new version of Compose, clickable Modifier shouldn't [work](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/material/material/src/commonMain/kotlin/androidx/compose/material/Card.kt;l=40?q=card%20compose) ([commit](https://android-review.googlesource.com/c/platform/frameworks/support/+/1660323/)). Use another overload of Card:
```
Card(onClick={})
```

Clickable modifier for Surfacer/Card isn't the right approach, because in this case Surface doesn't clip the indication (ripple) effect (indication draws over elevation/borders/rounded corners).

P.S. some other modifiers don't work too, because Surface overrides them: `background`/`border`/`clip`/`shadow`

**Comment by Syer10** [comment]
I see, ill wait for the next compose-jb build then, because it looks like the new card and surface overloads are not added yet

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5419">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
