### ISSUE TITLE
Web: getValue function with @Composable crashes at runtime

### ISSUE THREAD

**Issue by hfhbd** [JetBrains/compose-jb#827]
Hey, 
I want to annotate `operator fun getValue(ref: Any?, property: KProperty<*>): Router` with `@Composable`
Unfortunately, this idea crashes at runtime, when the `ComposableGroup` needs to recompose.

```kotlin
public companion object {
    @Composable
    public operator fun getValue(ref: Any?, property: KProperty<*>): Router {
        return RouterCompositionLocal.current
    }
}
```

Error: `TypeError: undefined is not an object (evaluating '$composer_0.startReplaceableGroup_0')`

```javascript
function Companion_41() {
    Companion_instance_40 = this;
}

Companion_41.prototype.getValue_2 = function (ref, property) {
illegalDecoyCallException('getValue');
};

Companion_41.prototype.getValue$composable = function (ref, property, $composer, $changed) {
    var $composer_0 = $composer;
    $composer_0.startReplaceableGroup_0(-1408373553);
    sourceInformation($composer_0, 'C(getValue$composable)P(1)');
    var tmp0_$get_current$$composable_0 = RouterCompositionLocal;
    var tmp1_$get_current$$composable_0 = $composer_0;
    var tmp2_$get_current$$composable_0 = 6;
    var $composer_1 = tmp1_$get_current$$composable_0;
    sourceInformationMarkerStart($composer_1, -304541069, 'C($get-current$$composable):CompositionLocal.kt#9igjgp');
    var tmp0_2 = $composer_1.consume_0(tmp0_$get_current$$composable_0);
    sourceInformationMarkerEnd($composer_1);
    var tmp0 = tmp0_2;
    $composer_0.endReplaceableGroup_0();
    return tmp0;
};
```

Sample project: https://github.com/hfhbd/routing-compose/tree/getByRouter
File: https://github.com/hfhbd/routing-compose/blob/getByRouter/src/jsMain/kotlin/app/softwork/routingcompose/Router.kt

**Comment by ryihan** [comment]
prototype function some error....

**Comment by olonho** [comment]
Not sure if it's intended usage of getValue delegate. Please check with Google developers.

**Comment by jimgoog** [comment]
Errrum, I don't see anything fundamentally wrong there (in theory it should work, but I'm not even remotely surprised it doesn't work), looks like an obscure bug due to no one ever having tried such a thing.  Probably technically a bug, albeit maybe a low priority one.

For others who are following along at home... Just ensure you aren't being "too clever by half".  Property delegates and operator overloading are niche topics and very often/easily abused, to the detriment of of code readability/understandability/maintainability.  Also, having Composables which return a value is a tiny bit sketchy in-and-of-itself.  Although it isn't wrong and is a supported feature, ideally no Composable functions would ever return a value; they would just emit UI.

If this ends up being an issue in upstream compiler (eg. reproducible on Android) then feel free to file a bug in Compose upstream.

**Comment by akurasov** [comment]
@hfhbd is your code still available somewhere? github says it doesn't exist anymore

**Comment by hfhbd** [comment]
@akurasov ups, after Jims answer I override the branch with a "normal" not "too clever by half" approach :D
[routing-composeByBug.zip](https://github.com/JetBrains/compose-jb/files/6822059/routing-composeByBug.zip)

**Comment by akurasov** [comment]
@hfhbd thank you! Am I understand right, that the only purpose of such construction is to use 
val router by Router
instead of 
val router = RouterCompositionLocal.current ?

**Comment by hfhbd** [comment]
@akurasov Yes, this was my intention.

**Comment by akurasov** [comment]
@hfhbd 
I think this will not work, since Composable attribute basically means that a Composer object will be implicitly passed to the function. But this operator doesn't assume that anything besides its parameters is passed to it. I checked it on Android and it crashes too. If you believe, that such possibility is important, you should raise this question to Google(Jetpack Compose team) and explain its importance to them. If they agree with you and support it, most probably this will automatically work on other platforms.

**Comment by jimgoog** [comment]
If it crashes on Android, please file a bug at https://issuetracker.google.com/issues/new?component=612128 with a minimal android repro.

**Comment by akurasov** [comment]
@jimgoog, as I said, I do not consider it a bug, thus I will not be able to explain Google team what I want from them. If you believe that this is a bug and ready to explain them why, please contact them directly.

**Comment by hfhbd** [comment]
https://issuetracker.google.com/issues/193814315

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-6374">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
