### ISSUE TITLE
Close window without terminating application

### ISSUE THREAD

**Issue by stoddartaw** [JetBrains/compose-jb#898]
Hi, I have a setup in which I have a long running service and want it to be able to spawn compose windows. The issue that I am facing is that when the window is closed, the whole process exits.

Is there a way around this other than creating two programs?

Here is the basic setup:

```
fun main() {
    Window {
        var text by remember { mutableStateOf("Hello, World!") }

        MaterialTheme {
            Button(onClick = {
                text = "Hello, Desktop!"
            }) {
                Text(text)
            }
        }
    }

    embeddedServer(Netty, port = 8080, host = "0.0.0.0") {
        configureSerialization()
        configureRouting()
        configureSockets()
    }.start(wait = true)
}
```

**Comment by akurasov** [comment]
Hi! 

Try the new Window API. There you can override actions that happens when window is closed. 

E.g. see https://github.com/JetBrains/compose-jb/tree/master/tutorials/Window_API_new
section "If you don't need to close the window and just need to hide it (for example to the tray), you can change the windowState.isVisible state:"

**Comment by stoddartaw** [comment]
Thanks @akurasov this looks promising. I can hide or close the window without the program exiting using this, so I'm closing this issue for now.

**Comment by okushnikov** [comment]
Please check the <a href="https://youtrack.jetbrains.com/issue/CMP-5345">following ticket</a> on YouTrack for follow-ups to this issue. GitHub issues will be closed in the coming weeks.
