### ISSUE TITLE
web: add a convenient api for data attributes

### ISSUE THREAD

**Issue by eymar** [JetBrains/compose-jb#926]
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/data-*

**Comment by Schahen** [comment]
relevant link https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

**Comment by Schahen** [comment]
Let's design this before rushing in. It's important to have a common understanding of what exactly  we do consider to be "convenient API"  ; )
So, there's a special family of `data-`-prefixed attributes, and such attributes differ from "regular" attributes in following ways:

1.  They can be accessed via special syntax, through the dataset object. 
2.  You can refer any attribute in the [content: attr](https://developer.mozilla.org/en-US/docs/Web/CSS/attr()) but it sort of best practice to refer data attributes there (is it so? - this is just my hypothesis)

The  №2 seems  to be out of scope of this particular task (though it makes sense to create a task about supporting content, both text and attr-ed in our CSS API), so let's discuss №1. 

So, consider following html:
```html
<article
  id="electric-cars"
  data-columns="3"
  data-index-number="12314"
  data-parent="cars">
</article>
```
Now, imagine that we have some sort of special getElement function that returns an element where all dataset properties are already bound to a specific interface, so that we write something like `val a = getElement<SomeDataSetInterface>([some selector])`. Well, it's doable, but we are talking about Compose and I just don't see a place where this is applicable to our workflow.  So, what exactly we want to do? Imagine, we have specialised Div, Span etc. composable funs and in all of them you can set  the type of dataset. But we don't have in Kotlin neither default nor nullable type params, so such syntax would be verbose - and this verbosity is not justified, since usually you don't have data attributes you need to access. 

If we want to set data attributes directly, to have something like `dataAttr`  - I'm not sure what exactly we'll wen compared to just using attr - but, again, let's discuss.

**Comment by eymar** [comment]
closing for now. We'll revisit this when necessary.
